//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        private System.DateTime FechaNacimientoField;
        
        private char SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public char Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusResponce", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StatusResponce : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Especialidad", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Especialidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdEspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdEspecialidad {
            get {
                return this.IdEspecialidadField;
            }
            set {
                if ((this.IdEspecialidadField.Equals(value) != true)) {
                    this.IdEspecialidadField = value;
                    this.RaisePropertyChanged("IdEspecialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoraAtencion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HoraAtencion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceCliente.Terapeuta IdTerapeutaField;
        
        private int IdHoraField;
        
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceCliente.Bloque IdBloqueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WindowsFormsApp1.ServiceCliente.Terapeuta IdTerapeuta {
            get {
                return this.IdTerapeutaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTerapeutaField, value) != true)) {
                    this.IdTerapeutaField = value;
                    this.RaisePropertyChanged("IdTerapeuta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdHora {
            get {
                return this.IdHoraField;
            }
            set {
                if ((this.IdHoraField.Equals(value) != true)) {
                    this.IdHoraField = value;
                    this.RaisePropertyChanged("IdHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WindowsFormsApp1.ServiceCliente.Bloque IdBloque {
            get {
                return this.IdBloqueField;
            }
            set {
                if ((object.ReferenceEquals(this.IdBloqueField, value) != true)) {
                    this.IdBloqueField = value;
                    this.RaisePropertyChanged("IdBloque");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Terapeuta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Terapeuta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdTerapeutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceCliente.Especialidad IdEspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceCliente.Usuario IdUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTerapeuta {
            get {
                return this.IdTerapeutaField;
            }
            set {
                if ((this.IdTerapeutaField.Equals(value) != true)) {
                    this.IdTerapeutaField = value;
                    this.RaisePropertyChanged("IdTerapeuta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WindowsFormsApp1.ServiceCliente.Especialidad IdEspecialidad {
            get {
                return this.IdEspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.IdEspecialidadField, value) != true)) {
                    this.IdEspecialidadField = value;
                    this.RaisePropertyChanged("IdEspecialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WindowsFormsApp1.ServiceCliente.Usuario IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bloque", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Bloque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdBloqueField;
        
        private int HoraInicioField;
        
        private int HoraFinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdBloque {
            get {
                return this.IdBloqueField;
            }
            set {
                if ((this.IdBloqueField.Equals(value) != true)) {
                    this.IdBloqueField = value;
                    this.RaisePropertyChanged("IdBloque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((this.HoraInicioField.Equals(value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((this.HoraFinField.Equals(value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUsuarioField;
        
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceCliente.RolUsuario IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceCliente.Persona IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WindowsFormsApp1.ServiceCliente.RolUsuario IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRolField, value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WindowsFormsApp1.ServiceCliente.Persona IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPersonaField, value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolUsuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RolUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceCliente.HoraAtencion IdHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceCliente.Persona IdPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceCliente.EstadoReserva IdEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdReserva {
            get {
                return this.IdReservaField;
            }
            set {
                if ((this.IdReservaField.Equals(value) != true)) {
                    this.IdReservaField = value;
                    this.RaisePropertyChanged("IdReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WindowsFormsApp1.ServiceCliente.HoraAtencion IdHora {
            get {
                return this.IdHoraField;
            }
            set {
                if ((object.ReferenceEquals(this.IdHoraField, value) != true)) {
                    this.IdHoraField = value;
                    this.RaisePropertyChanged("IdHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WindowsFormsApp1.ServiceCliente.Persona IdPaciente {
            get {
                return this.IdPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPacienteField, value) != true)) {
                    this.IdPacienteField = value;
                    this.RaisePropertyChanged("IdPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WindowsFormsApp1.ServiceCliente.EstadoReserva IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdEstadoField, value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoReserva", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EstadoReserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCliente.WebServiceClienteSoap")]
    public interface WebServiceClienteSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApp1.ServiceCliente.HelloWorldResponse HelloWorld(WindowsFormsApp1.ServiceCliente.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.HelloWorldResponse> HelloWorldAsync(WindowsFormsApp1.ServiceCliente.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento persona del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarPacienteService", ReplyAction="*")]
        WindowsFormsApp1.ServiceCliente.registrarPacienteServiceResponse registrarPacienteService(WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.registrarPacienteServiceResponse> registrarPacienteServiceAsync(WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento especialidad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarHorasDisponiblesService", ReplyAction="*")]
        WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceResponse buscarHorasDisponiblesService(WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarHorasDisponiblesService", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceResponse> buscarHorasDisponiblesServiceAsync(WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento generarListaEspecialidadServiceResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarListaEspecialidadService", ReplyAction="*")]
        WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceResponse generarListaEspecialidadService(WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarListaEspecialidadService", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceResponse> generarListaEspecialidadServiceAsync(WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento generarListaEspecialistaServiceResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarListaEspecialistaService", ReplyAction="*")]
        WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceResponse generarListaEspecialistaService(WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarListaEspecialistaService", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceResponse> generarListaEspecialistaServiceAsync(WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPacienteService", ReplyAction="*")]
        WindowsFormsApp1.ServiceCliente.buscarPacienteServiceResponse buscarPacienteService(WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.buscarPacienteServiceResponse> buscarPacienteServiceAsync(WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaReservasPorRutService", ReplyAction="*")]
        WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceResponse listaReservasPorRutService(WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaReservasPorRutService", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceResponse> listaReservasPorRutServiceAsync(WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rechazarConfirmarReservaServiceResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rechazarConfirmarReservaService", ReplyAction="*")]
        WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceResponse rechazarConfirmarReservaService(WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rechazarConfirmarReservaService", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceResponse> rechazarConfirmarReservaServiceAsync(WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApp1.ServiceCliente.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApp1.ServiceCliente.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarPacienteServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarPacienteService", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequestBody Body;
        
        public registrarPacienteServiceRequest() {
        }
        
        public registrarPacienteServiceRequest(WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarPacienteServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceCliente.Persona persona;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idHoraAtencion;
        
        public registrarPacienteServiceRequestBody() {
        }
        
        public registrarPacienteServiceRequestBody(WindowsFormsApp1.ServiceCliente.Persona persona, int idHoraAtencion) {
            this.persona = persona;
            this.idHoraAtencion = idHoraAtencion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarPacienteServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarPacienteServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.registrarPacienteServiceResponseBody Body;
        
        public registrarPacienteServiceResponse() {
        }
        
        public registrarPacienteServiceResponse(WindowsFormsApp1.ServiceCliente.registrarPacienteServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarPacienteServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceCliente.StatusResponce registrarPacienteServiceResult;
        
        public registrarPacienteServiceResponseBody() {
        }
        
        public registrarPacienteServiceResponseBody(WindowsFormsApp1.ServiceCliente.StatusResponce registrarPacienteServiceResult) {
            this.registrarPacienteServiceResult = registrarPacienteServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarHorasDisponiblesServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarHorasDisponiblesService", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequestBody Body;
        
        public buscarHorasDisponiblesServiceRequest() {
        }
        
        public buscarHorasDisponiblesServiceRequest(WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarHorasDisponiblesServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceCliente.Especialidad especialidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<System.DateTime> fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WindowsFormsApp1.ServiceCliente.Persona persona;
        
        public buscarHorasDisponiblesServiceRequestBody() {
        }
        
        public buscarHorasDisponiblesServiceRequestBody(WindowsFormsApp1.ServiceCliente.Especialidad especialidad, System.Nullable<System.DateTime> fecha, WindowsFormsApp1.ServiceCliente.Persona persona) {
            this.especialidad = especialidad;
            this.fecha = fecha;
            this.persona = persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarHorasDisponiblesServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarHorasDisponiblesServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceResponseBody Body;
        
        public buscarHorasDisponiblesServiceResponse() {
        }
        
        public buscarHorasDisponiblesServiceResponse(WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarHorasDisponiblesServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceCliente.HoraAtencion[] buscarHorasDisponiblesServiceResult;
        
        public buscarHorasDisponiblesServiceResponseBody() {
        }
        
        public buscarHorasDisponiblesServiceResponseBody(WindowsFormsApp1.ServiceCliente.HoraAtencion[] buscarHorasDisponiblesServiceResult) {
            this.buscarHorasDisponiblesServiceResult = buscarHorasDisponiblesServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarListaEspecialidadServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarListaEspecialidadService", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequestBody Body;
        
        public generarListaEspecialidadServiceRequest() {
        }
        
        public generarListaEspecialidadServiceRequest(WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class generarListaEspecialidadServiceRequestBody {
        
        public generarListaEspecialidadServiceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarListaEspecialidadServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarListaEspecialidadServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceResponseBody Body;
        
        public generarListaEspecialidadServiceResponse() {
        }
        
        public generarListaEspecialidadServiceResponse(WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class generarListaEspecialidadServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceCliente.Especialidad[] generarListaEspecialidadServiceResult;
        
        public generarListaEspecialidadServiceResponseBody() {
        }
        
        public generarListaEspecialidadServiceResponseBody(WindowsFormsApp1.ServiceCliente.Especialidad[] generarListaEspecialidadServiceResult) {
            this.generarListaEspecialidadServiceResult = generarListaEspecialidadServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarListaEspecialistaServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarListaEspecialistaService", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequestBody Body;
        
        public generarListaEspecialistaServiceRequest() {
        }
        
        public generarListaEspecialistaServiceRequest(WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class generarListaEspecialistaServiceRequestBody {
        
        public generarListaEspecialistaServiceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarListaEspecialistaServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarListaEspecialistaServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceResponseBody Body;
        
        public generarListaEspecialistaServiceResponse() {
        }
        
        public generarListaEspecialistaServiceResponse(WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class generarListaEspecialistaServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceCliente.Terapeuta[] generarListaEspecialistaServiceResult;
        
        public generarListaEspecialistaServiceResponseBody() {
        }
        
        public generarListaEspecialistaServiceResponseBody(WindowsFormsApp1.ServiceCliente.Terapeuta[] generarListaEspecialistaServiceResult) {
            this.generarListaEspecialistaServiceResult = generarListaEspecialistaServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarPacienteServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarPacienteService", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequestBody Body;
        
        public buscarPacienteServiceRequest() {
        }
        
        public buscarPacienteServiceRequest(WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarPacienteServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public buscarPacienteServiceRequestBody() {
        }
        
        public buscarPacienteServiceRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarPacienteServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarPacienteServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.buscarPacienteServiceResponseBody Body;
        
        public buscarPacienteServiceResponse() {
        }
        
        public buscarPacienteServiceResponse(WindowsFormsApp1.ServiceCliente.buscarPacienteServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarPacienteServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceCliente.Persona buscarPacienteServiceResult;
        
        public buscarPacienteServiceResponseBody() {
        }
        
        public buscarPacienteServiceResponseBody(WindowsFormsApp1.ServiceCliente.Persona buscarPacienteServiceResult) {
            this.buscarPacienteServiceResult = buscarPacienteServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaReservasPorRutServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaReservasPorRutService", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequestBody Body;
        
        public listaReservasPorRutServiceRequest() {
        }
        
        public listaReservasPorRutServiceRequest(WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listaReservasPorRutServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public listaReservasPorRutServiceRequestBody() {
        }
        
        public listaReservasPorRutServiceRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaReservasPorRutServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaReservasPorRutServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceResponseBody Body;
        
        public listaReservasPorRutServiceResponse() {
        }
        
        public listaReservasPorRutServiceResponse(WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listaReservasPorRutServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceCliente.Reserva[] listaReservasPorRutServiceResult;
        
        public listaReservasPorRutServiceResponseBody() {
        }
        
        public listaReservasPorRutServiceResponseBody(WindowsFormsApp1.ServiceCliente.Reserva[] listaReservasPorRutServiceResult) {
            this.listaReservasPorRutServiceResult = listaReservasPorRutServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rechazarConfirmarReservaServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rechazarConfirmarReservaService", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequestBody Body;
        
        public rechazarConfirmarReservaServiceRequest() {
        }
        
        public rechazarConfirmarReservaServiceRequest(WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rechazarConfirmarReservaServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public char cambioEstado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idReserva;
        
        public rechazarConfirmarReservaServiceRequestBody() {
        }
        
        public rechazarConfirmarReservaServiceRequestBody(char cambioEstado, int idReserva) {
            this.cambioEstado = cambioEstado;
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rechazarConfirmarReservaServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rechazarConfirmarReservaServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceResponseBody Body;
        
        public rechazarConfirmarReservaServiceResponse() {
        }
        
        public rechazarConfirmarReservaServiceResponse(WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rechazarConfirmarReservaServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceCliente.StatusResponce rechazarConfirmarReservaServiceResult;
        
        public rechazarConfirmarReservaServiceResponseBody() {
        }
        
        public rechazarConfirmarReservaServiceResponseBody(WindowsFormsApp1.ServiceCliente.StatusResponce rechazarConfirmarReservaServiceResult) {
            this.rechazarConfirmarReservaServiceResult = rechazarConfirmarReservaServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceClienteSoapChannel : WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClienteSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap>, WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap {
        
        public WebServiceClienteSoapClient() {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceCliente.HelloWorldResponse WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.HelloWorld(WindowsFormsApp1.ServiceCliente.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApp1.ServiceCliente.HelloWorldRequest inValue = new WindowsFormsApp1.ServiceCliente.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.HelloWorldRequestBody();
            WindowsFormsApp1.ServiceCliente.HelloWorldResponse retVal = ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.HelloWorldResponse> WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.HelloWorldAsync(WindowsFormsApp1.ServiceCliente.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsApp1.ServiceCliente.HelloWorldRequest inValue = new WindowsFormsApp1.ServiceCliente.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.HelloWorldRequestBody();
            return ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceCliente.registrarPacienteServiceResponse WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.registrarPacienteService(WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequest request) {
            return base.Channel.registrarPacienteService(request);
        }
        
        public WindowsFormsApp1.ServiceCliente.StatusResponce registrarPacienteService(WindowsFormsApp1.ServiceCliente.Persona persona, int idHoraAtencion) {
            WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequestBody();
            inValue.Body.persona = persona;
            inValue.Body.idHoraAtencion = idHoraAtencion;
            WindowsFormsApp1.ServiceCliente.registrarPacienteServiceResponse retVal = ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).registrarPacienteService(inValue);
            return retVal.Body.registrarPacienteServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.registrarPacienteServiceResponse> WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.registrarPacienteServiceAsync(WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequest request) {
            return base.Channel.registrarPacienteServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.registrarPacienteServiceResponse> registrarPacienteServiceAsync(WindowsFormsApp1.ServiceCliente.Persona persona, int idHoraAtencion) {
            WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.registrarPacienteServiceRequestBody();
            inValue.Body.persona = persona;
            inValue.Body.idHoraAtencion = idHoraAtencion;
            return ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).registrarPacienteServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceResponse WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.buscarHorasDisponiblesService(WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequest request) {
            return base.Channel.buscarHorasDisponiblesService(request);
        }
        
        public WindowsFormsApp1.ServiceCliente.HoraAtencion[] buscarHorasDisponiblesService(WindowsFormsApp1.ServiceCliente.Especialidad especialidad, System.Nullable<System.DateTime> fecha, WindowsFormsApp1.ServiceCliente.Persona persona) {
            WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequestBody();
            inValue.Body.especialidad = especialidad;
            inValue.Body.fecha = fecha;
            inValue.Body.persona = persona;
            WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceResponse retVal = ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).buscarHorasDisponiblesService(inValue);
            return retVal.Body.buscarHorasDisponiblesServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceResponse> WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.buscarHorasDisponiblesServiceAsync(WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequest request) {
            return base.Channel.buscarHorasDisponiblesServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceResponse> buscarHorasDisponiblesServiceAsync(WindowsFormsApp1.ServiceCliente.Especialidad especialidad, System.Nullable<System.DateTime> fecha, WindowsFormsApp1.ServiceCliente.Persona persona) {
            WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.buscarHorasDisponiblesServiceRequestBody();
            inValue.Body.especialidad = especialidad;
            inValue.Body.fecha = fecha;
            inValue.Body.persona = persona;
            return ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).buscarHorasDisponiblesServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceResponse WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.generarListaEspecialidadService(WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequest request) {
            return base.Channel.generarListaEspecialidadService(request);
        }
        
        public WindowsFormsApp1.ServiceCliente.Especialidad[] generarListaEspecialidadService() {
            WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequestBody();
            WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceResponse retVal = ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).generarListaEspecialidadService(inValue);
            return retVal.Body.generarListaEspecialidadServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceResponse> WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.generarListaEspecialidadServiceAsync(WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequest request) {
            return base.Channel.generarListaEspecialidadServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceResponse> generarListaEspecialidadServiceAsync() {
            WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.generarListaEspecialidadServiceRequestBody();
            return ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).generarListaEspecialidadServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceResponse WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.generarListaEspecialistaService(WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequest request) {
            return base.Channel.generarListaEspecialistaService(request);
        }
        
        public WindowsFormsApp1.ServiceCliente.Terapeuta[] generarListaEspecialistaService() {
            WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequestBody();
            WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceResponse retVal = ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).generarListaEspecialistaService(inValue);
            return retVal.Body.generarListaEspecialistaServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceResponse> WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.generarListaEspecialistaServiceAsync(WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequest request) {
            return base.Channel.generarListaEspecialistaServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceResponse> generarListaEspecialistaServiceAsync() {
            WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.generarListaEspecialistaServiceRequestBody();
            return ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).generarListaEspecialistaServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceCliente.buscarPacienteServiceResponse WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.buscarPacienteService(WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequest request) {
            return base.Channel.buscarPacienteService(request);
        }
        
        public WindowsFormsApp1.ServiceCliente.Persona buscarPacienteService(string rut) {
            WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequestBody();
            inValue.Body.rut = rut;
            WindowsFormsApp1.ServiceCliente.buscarPacienteServiceResponse retVal = ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).buscarPacienteService(inValue);
            return retVal.Body.buscarPacienteServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.buscarPacienteServiceResponse> WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.buscarPacienteServiceAsync(WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequest request) {
            return base.Channel.buscarPacienteServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.buscarPacienteServiceResponse> buscarPacienteServiceAsync(string rut) {
            WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.buscarPacienteServiceRequestBody();
            inValue.Body.rut = rut;
            return ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).buscarPacienteServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceResponse WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.listaReservasPorRutService(WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequest request) {
            return base.Channel.listaReservasPorRutService(request);
        }
        
        public WindowsFormsApp1.ServiceCliente.Reserva[] listaReservasPorRutService(string rut) {
            WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequestBody();
            inValue.Body.rut = rut;
            WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceResponse retVal = ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).listaReservasPorRutService(inValue);
            return retVal.Body.listaReservasPorRutServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceResponse> WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.listaReservasPorRutServiceAsync(WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequest request) {
            return base.Channel.listaReservasPorRutServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceResponse> listaReservasPorRutServiceAsync(string rut) {
            WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.listaReservasPorRutServiceRequestBody();
            inValue.Body.rut = rut;
            return ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).listaReservasPorRutServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceResponse WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.rechazarConfirmarReservaService(WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequest request) {
            return base.Channel.rechazarConfirmarReservaService(request);
        }
        
        public WindowsFormsApp1.ServiceCliente.StatusResponce rechazarConfirmarReservaService(char cambioEstado, int idReserva) {
            WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequestBody();
            inValue.Body.cambioEstado = cambioEstado;
            inValue.Body.idReserva = idReserva;
            WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceResponse retVal = ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).rechazarConfirmarReservaService(inValue);
            return retVal.Body.rechazarConfirmarReservaServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceResponse> WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap.rechazarConfirmarReservaServiceAsync(WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequest request) {
            return base.Channel.rechazarConfirmarReservaServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceResponse> rechazarConfirmarReservaServiceAsync(char cambioEstado, int idReserva) {
            WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequest inValue = new WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceCliente.rechazarConfirmarReservaServiceRequestBody();
            inValue.Body.cambioEstado = cambioEstado;
            inValue.Body.idReserva = idReserva;
            return ((WindowsFormsApp1.ServiceCliente.WebServiceClienteSoap)(this)).rechazarConfirmarReservaServiceAsync(inValue);
        }
    }
}
