//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicioPresentacionWeb.ServiceCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCliente.WebServiceClienteSoap")]
    public interface WebServiceClienteSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje AutenticacionUsuarioRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutenticacionUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.AutenticacionUsuarioResponse AutenticacionUsuario(CapaServicioPresentacionWeb.ServiceCliente.AutenticacionUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.StatusResponce registrarPacienteService(CapaServicioPresentacionWeb.ServiceCliente.Paciente persona, int idHoraAtencion);
        
        // CODEGEN: El parámetro 'fecha' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarHorasDisponiblesService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.buscarHorasDisponiblesServiceResponse buscarHorasDisponiblesService(CapaServicioPresentacionWeb.ServiceCliente.buscarHorasDisponiblesServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleHoraService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.HoraAtencion buscarDetalleHoraService(int idHoraAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarListaEspecialidadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.EspecialidadClinica[] generarListaEspecialidadService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarListaEspecialistaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.EspecialidadTerapeuta[] generarListaEspecialistaService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.Paciente buscarPacienteService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaReservasPorRutAndCorreoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.HoraAtencion[] listaReservasPorRutAndCorreoService(string rut, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rechazarConfirmarReservaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.StatusResponce rechazarConfirmarReservaService(char cambioEstado, int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarListaMedioPagoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.MedioPago[] generarListaMedioPagoService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarVentaRealizadaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.StatusResponce guardarVentaRealizadaService(CapaServicioPresentacionWeb.ServiceCliente.Venta venta, int[] idHora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/horasPorRutPacienteMasVentaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.HoraAtencion[] horasPorRutPacienteMasVentaService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregarEmpleadoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.StatusResponce agregarEmpleadoService(CapaServicioPresentacionWeb.ServiceCliente.Empleado empleado);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje loginServiceRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioPresentacionWeb.ServiceCliente.loginServiceResponse loginService(CapaServicioPresentacionWeb.ServiceCliente.loginServiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TokenSecurity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stTokenField;
        
        private string autenticacionTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StToken {
            get {
                return this.stTokenField;
            }
            set {
                this.stTokenField = value;
                this.RaisePropertyChanged("StToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AutenticacionToken {
            get {
                return this.autenticacionTokenField;
            }
            set {
                this.autenticacionTokenField = value;
                this.RaisePropertyChanged("AutenticacionToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EspecialidadTerapeuta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEspecialidadTerapeutaField;
        
        private EspecialidadClinica especialidadClinicaField;
        
        private Empleado empleadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdEspecialidadTerapeuta {
            get {
                return this.idEspecialidadTerapeutaField;
            }
            set {
                this.idEspecialidadTerapeutaField = value;
                this.RaisePropertyChanged("IdEspecialidadTerapeuta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EspecialidadClinica EspecialidadClinica {
            get {
                return this.especialidadClinicaField;
            }
            set {
                this.especialidadClinicaField = value;
                this.RaisePropertyChanged("EspecialidadClinica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Empleado Empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("Empleado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EspecialidadClinica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int precioField;
        
        private int idEspecialidadClinicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("Precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdEspecialidadClinica {
            get {
                return this.idEspecialidadClinicaField;
            }
            set {
                this.idEspecialidadClinicaField = value;
                this.RaisePropertyChanged("IdEspecialidadClinica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEmpleadoField;
        
        private string usuarioField;
        
        private string contraseñaField;
        
        private string nombreField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private int telefonoField;
        
        private string correoField;
        
        private string fechaNacimientoField;
        
        private Cargo cargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("IdEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("Contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ApellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("ApellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ApellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("ApellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("FechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Cargo Cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("Cargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idCargoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdCargo {
            get {
                return this.idCargoField;
            }
            set {
                this.idCargoField = value;
                this.RaisePropertyChanged("IdCargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MedioPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idMedioPagoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdMedioPago {
            get {
                return this.idMedioPagoField;
            }
            set {
                this.idMedioPagoField = value;
                this.RaisePropertyChanged("IdMedioPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoVenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEstadoVentaField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdEstadoVenta {
            get {
                return this.idEstadoVentaField;
            }
            set {
                this.idEstadoVentaField = value;
                this.RaisePropertyChanged("IdEstadoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Venta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idVentaField;
        
        private System.DateTime fechaPagoField;
        
        private int montoField;
        
        private EstadoVenta estadoVentaField;
        
        private MedioPago medioPagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdVenta {
            get {
                return this.idVentaField;
            }
            set {
                this.idVentaField = value;
                this.RaisePropertyChanged("IdVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime FechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
                this.RaisePropertyChanged("FechaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("Monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public EstadoVenta EstadoVenta {
            get {
                return this.estadoVentaField;
            }
            set {
                this.estadoVentaField = value;
                this.RaisePropertyChanged("EstadoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MedioPago MedioPago {
            get {
                return this.medioPagoField;
            }
            set {
                this.medioPagoField = value;
                this.RaisePropertyChanged("MedioPago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sala : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idSalaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdSala {
            get {
                return this.idSalaField;
            }
            set {
                this.idSalaField = value;
                this.RaisePropertyChanged("IdSala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoReserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEstadoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("IdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bloque : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idBloqueField;
        
        private int horaInicioField;
        
        private int horaFinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdBloque {
            get {
                return this.idBloqueField;
            }
            set {
                this.idBloqueField = value;
                this.RaisePropertyChanged("IdBloque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int HoraInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("HoraInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int HoraFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("HoraFin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HoraAtencion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idHoraField;
        
        private System.DateTime fechaField;
        
        private Bloque idBloqueField;
        
        private Paciente pacienteField;
        
        private EstadoReserva estadoReservaField;
        
        private EspecialidadClinica especialidadClinicaField;
        
        private Empleado terapeutaField;
        
        private Sala salaField;
        
        private Venta ventaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdHora {
            get {
                return this.idHoraField;
            }
            set {
                this.idHoraField = value;
                this.RaisePropertyChanged("IdHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Bloque IdBloque {
            get {
                return this.idBloqueField;
            }
            set {
                this.idBloqueField = value;
                this.RaisePropertyChanged("IdBloque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
                this.RaisePropertyChanged("Paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public EstadoReserva EstadoReserva {
            get {
                return this.estadoReservaField;
            }
            set {
                this.estadoReservaField = value;
                this.RaisePropertyChanged("EstadoReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public EspecialidadClinica EspecialidadClinica {
            get {
                return this.especialidadClinicaField;
            }
            set {
                this.especialidadClinicaField = value;
                this.RaisePropertyChanged("EspecialidadClinica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Empleado Terapeuta {
            get {
                return this.terapeutaField;
            }
            set {
                this.terapeutaField = value;
                this.RaisePropertyChanged("Terapeuta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Sala Sala {
            get {
                return this.salaField;
            }
            set {
                this.salaField = value;
                this.RaisePropertyChanged("Sala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Venta Venta {
            get {
                return this.ventaField;
            }
            set {
                this.ventaField = value;
                this.RaisePropertyChanged("Venta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string nombreField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string telefonoField;
        
        private System.DateTime fechaNacimientoField;
        
        private char sexoField;
        
        private string correoField;
        
        private int idPacienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ApellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("ApellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ApellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("ApellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("FechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public char Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int IdPaciente {
            get {
                return this.idPacienteField;
            }
            set {
                this.idPacienteField = value;
                this.RaisePropertyChanged("IdPaciente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusResponce : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticacionUsuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticacionUsuarioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public CapaServicioPresentacionWeb.ServiceCliente.TokenSecurity TokenSecurity;
        
        public AutenticacionUsuarioRequest() {
        }
        
        public AutenticacionUsuarioRequest(CapaServicioPresentacionWeb.ServiceCliente.TokenSecurity TokenSecurity) {
            this.TokenSecurity = TokenSecurity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticacionUsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticacionUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AutenticacionUsuarioResult;
        
        public AutenticacionUsuarioResponse() {
        }
        
        public AutenticacionUsuarioResponse(string AutenticacionUsuarioResult) {
            this.AutenticacionUsuarioResult = AutenticacionUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarHorasDisponiblesService", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class buscarHorasDisponiblesServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CapaServicioPresentacionWeb.ServiceCliente.EspecialidadClinica especialidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public CapaServicioPresentacionWeb.ServiceCliente.Empleado persona;
        
        public buscarHorasDisponiblesServiceRequest() {
        }
        
        public buscarHorasDisponiblesServiceRequest(CapaServicioPresentacionWeb.ServiceCliente.EspecialidadClinica especialidad, System.Nullable<System.DateTime> fecha, CapaServicioPresentacionWeb.ServiceCliente.Empleado persona) {
            this.especialidad = especialidad;
            this.fecha = fecha;
            this.persona = persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarHorasDisponiblesServiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class buscarHorasDisponiblesServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CapaServicioPresentacionWeb.ServiceCliente.HoraAtencion[] buscarHorasDisponiblesServiceResult;
        
        public buscarHorasDisponiblesServiceResponse() {
        }
        
        public buscarHorasDisponiblesServiceResponse(CapaServicioPresentacionWeb.ServiceCliente.HoraAtencion[] buscarHorasDisponiblesServiceResult) {
            this.buscarHorasDisponiblesServiceResult = buscarHorasDisponiblesServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginService", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class loginServiceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public CapaServicioPresentacionWeb.ServiceCliente.TokenSecurity TokenSecurity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public loginServiceRequest() {
        }
        
        public loginServiceRequest(CapaServicioPresentacionWeb.ServiceCliente.TokenSecurity TokenSecurity, string usuario, string password) {
            this.TokenSecurity = TokenSecurity;
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginServiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class loginServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CapaServicioPresentacionWeb.ServiceCliente.Empleado loginServiceResult;
        
        public loginServiceResponse() {
        }
        
        public loginServiceResponse(CapaServicioPresentacionWeb.ServiceCliente.Empleado loginServiceResult) {
            this.loginServiceResult = loginServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceClienteSoapChannel : CapaServicioPresentacionWeb.ServiceCliente.WebServiceClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClienteSoapClient : System.ServiceModel.ClientBase<CapaServicioPresentacionWeb.ServiceCliente.WebServiceClienteSoap>, CapaServicioPresentacionWeb.ServiceCliente.WebServiceClienteSoap {
        
        public WebServiceClienteSoapClient() {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaServicioPresentacionWeb.ServiceCliente.AutenticacionUsuarioResponse CapaServicioPresentacionWeb.ServiceCliente.WebServiceClienteSoap.AutenticacionUsuario(CapaServicioPresentacionWeb.ServiceCliente.AutenticacionUsuarioRequest request) {
            return base.Channel.AutenticacionUsuario(request);
        }
        
        public string AutenticacionUsuario(CapaServicioPresentacionWeb.ServiceCliente.TokenSecurity TokenSecurity) {
            CapaServicioPresentacionWeb.ServiceCliente.AutenticacionUsuarioRequest inValue = new CapaServicioPresentacionWeb.ServiceCliente.AutenticacionUsuarioRequest();
            inValue.TokenSecurity = TokenSecurity;
            CapaServicioPresentacionWeb.ServiceCliente.AutenticacionUsuarioResponse retVal = ((CapaServicioPresentacionWeb.ServiceCliente.WebServiceClienteSoap)(this)).AutenticacionUsuario(inValue);
            return retVal.AutenticacionUsuarioResult;
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.StatusResponce registrarPacienteService(CapaServicioPresentacionWeb.ServiceCliente.Paciente persona, int idHoraAtencion) {
            return base.Channel.registrarPacienteService(persona, idHoraAtencion);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaServicioPresentacionWeb.ServiceCliente.buscarHorasDisponiblesServiceResponse CapaServicioPresentacionWeb.ServiceCliente.WebServiceClienteSoap.buscarHorasDisponiblesService(CapaServicioPresentacionWeb.ServiceCliente.buscarHorasDisponiblesServiceRequest request) {
            return base.Channel.buscarHorasDisponiblesService(request);
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.HoraAtencion[] buscarHorasDisponiblesService(CapaServicioPresentacionWeb.ServiceCliente.EspecialidadClinica especialidad, System.Nullable<System.DateTime> fecha, CapaServicioPresentacionWeb.ServiceCliente.Empleado persona) {
            CapaServicioPresentacionWeb.ServiceCliente.buscarHorasDisponiblesServiceRequest inValue = new CapaServicioPresentacionWeb.ServiceCliente.buscarHorasDisponiblesServiceRequest();
            inValue.especialidad = especialidad;
            inValue.fecha = fecha;
            inValue.persona = persona;
            CapaServicioPresentacionWeb.ServiceCliente.buscarHorasDisponiblesServiceResponse retVal = ((CapaServicioPresentacionWeb.ServiceCliente.WebServiceClienteSoap)(this)).buscarHorasDisponiblesService(inValue);
            return retVal.buscarHorasDisponiblesServiceResult;
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.HoraAtencion buscarDetalleHoraService(int idHoraAtencion) {
            return base.Channel.buscarDetalleHoraService(idHoraAtencion);
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.EspecialidadClinica[] generarListaEspecialidadService() {
            return base.Channel.generarListaEspecialidadService();
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.EspecialidadTerapeuta[] generarListaEspecialistaService() {
            return base.Channel.generarListaEspecialistaService();
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.Paciente buscarPacienteService(string rut) {
            return base.Channel.buscarPacienteService(rut);
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.HoraAtencion[] listaReservasPorRutAndCorreoService(string rut, string correo) {
            return base.Channel.listaReservasPorRutAndCorreoService(rut, correo);
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.StatusResponce rechazarConfirmarReservaService(char cambioEstado, int idReserva) {
            return base.Channel.rechazarConfirmarReservaService(cambioEstado, idReserva);
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.MedioPago[] generarListaMedioPagoService() {
            return base.Channel.generarListaMedioPagoService();
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.StatusResponce guardarVentaRealizadaService(CapaServicioPresentacionWeb.ServiceCliente.Venta venta, int[] idHora) {
            return base.Channel.guardarVentaRealizadaService(venta, idHora);
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.HoraAtencion[] horasPorRutPacienteMasVentaService(string rut) {
            return base.Channel.horasPorRutPacienteMasVentaService(rut);
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.StatusResponce agregarEmpleadoService(CapaServicioPresentacionWeb.ServiceCliente.Empleado empleado) {
            return base.Channel.agregarEmpleadoService(empleado);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaServicioPresentacionWeb.ServiceCliente.loginServiceResponse CapaServicioPresentacionWeb.ServiceCliente.WebServiceClienteSoap.loginService(CapaServicioPresentacionWeb.ServiceCliente.loginServiceRequest request) {
            return base.Channel.loginService(request);
        }
        
        public CapaServicioPresentacionWeb.ServiceCliente.Empleado loginService(CapaServicioPresentacionWeb.ServiceCliente.TokenSecurity TokenSecurity, string usuario, string password) {
            CapaServicioPresentacionWeb.ServiceCliente.loginServiceRequest inValue = new CapaServicioPresentacionWeb.ServiceCliente.loginServiceRequest();
            inValue.TokenSecurity = TokenSecurity;
            inValue.usuario = usuario;
            inValue.password = password;
            CapaServicioPresentacionWeb.ServiceCliente.loginServiceResponse retVal = ((CapaServicioPresentacionWeb.ServiceCliente.WebServiceClienteSoap)(this)).loginService(inValue);
            return retVal.loginServiceResult;
        }
    }
}
